# Generated by Django 6.0.5 on 2026-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('occupation', models.CharField(max_length=255)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('has_kids', models.BooleanField(default=False)),
                ('kids_info', models.TextField(blank=True, null=True)),
                ('pref_age', models.CharField(max_length=50)),
                ('pref_countries', models.CharField(max_length=255)),
                ('relationship_goal', models.CharField(choices=[('Marriage', 'Marriage'), ('Serious', 'Serious Relationship'), ('Friendship', 'Friendship')], max_length=20)),
                ('profile_photo', models.ImageField(upload_to='profiles/')),
                ('is_paid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
